### ISSUE TITLE
add support for custom tracks in builds.yaml

### ISSUE THREAD

**Issue by lucabello** [canonical/oci-factory#8]
### The current situation

Currently, the **builds.yaml** file allows to specify "risk levels" to publish to. For the following file:

```yaml
--- # builds.yaml
version: 1
images:
  - source: "canonical/prometheus-rock"
    commit: <some_sha>
    directory: 2.42.0
    release-to:
      risks:
        - stable
```
a new release will be generated, and the final image tag will be `2.42.0_22.04_stable`.

### The feature request

However, it's quite compelling for us to have support for custom tracks based on semantic versions.

What we would like to write is:

```yaml
--- # builds.yaml
version: 1
images:
  - source: "canonical/prometheus-rock"
    commit: <some_sha>
    directory: 2.42.0
    release-to:
      tracks:
        - 2.42.0/stable
        - 2.42/stable
        - 2/stable
```

This way, the CI should update **releases.yaml** to automatically create all those tracks, producing final tags of `2.42.0_22.04_stable`, `2.42_22.04_stable`, `2_22.04_stable`. Whenever a new version (e.g., 2.42.1) comes in, we would update the **builds.yaml** file as follows:

```yaml
--- # builds.yaml
version: 2
images:
  - source: "canonical/prometheus-rock"
    commit: <some_sha>
    directory: 2.42.0
    release-to:
      tracks:
        - 2.42.0/stable
  - source: "canonical/prometheus-rock"
    commit: <some_sha>
    directory: 2.42.1
    release-to:
      tracks:
        - 2.42.1/stable
        - 2.42/stable
        - 2/stable
```
**releases.yaml** should be automatically updated so that the new revisions are assigned to the specified tracks/risk levels.

This allows us to have:
* "major version tags" that point at the latest release for that major;
* "major.minor version tags" that point at the latest release for that major.minor.

**This should all happen in one PR, by only touching builds.yaml.**

### Potential problems and solutions

For this change to happen, a coordinate analysis with @cjdcordeiro showed a couple of things that need to be addressed:
* the revision number for new builds need to be automatically passed to the **releases.yaml** file (currently the process requires two separate PRs);
* a check needs to be enforced to make sure that **builds.yaml** is not trying to release different versions on the same track;
* to avoid polluting the tag namespace, a check needs to be enforced to make sure that custom tracks follow a specified naming convention (it was agreed upon that only allowing semantic version patterns is likely the way to go).

Two possible implementations of the automatic **releases.yaml** update would produce either of the following files:
```yaml
--- # releases.yaml (auto-updated, option 1)
version: '1'
channels:
  2.42.1_22.04:
    stable: 2
  2.42.0_22.04:
    stable: 1
  2.42_22.04:
    stable: 2
  2.42_22.04:
    stable: 2
--- # releases.yaml (auto-updated, option 2)
version: '1'
channels:
  2.42.1_22.04:
    stable: 2
  2.42.0_22.04:
    stable: 1
  2.42_22.04:
    stable: 2.42.1_22.04_stable
  2.42_22.04:
    stable: 2.42.1_22.04_stable
```

If you can't find the extra time for this, I'm happy to contribute to the change myself to make it happen as soon as possible!

**Comment by cjdcordeiro** [comment]
Thanks for proposing this. :eyes: 

Here are 2 scenarios I'm worried about:

```yaml
--- # builds.yaml
version: 1
images:
  - source: "canonical/prometheus-rock"
    commit: <some_sha>
    directory: 2.42.0
    release-to:
      tracks:
        ### BAD TRACK
        - 3.1.2/stable
        - 2.42/stable
        - 2/stable
```

and

```yaml
--- # builds.yaml
version: 1
images:
  - source: "canonical/prometheus-rock"
    commit: <some_sha>
    directory: 2.42.0
    release-to:
      tracks:
        ### MISSING THE "canonical" tag 2.42.0-<base>_risk
        - 2.42/stable
        - 2/stable
```

Sure, these two scenarios can be validated via CI...I just need to check how much effort and how reliable those checks would be...

---

one additional thing: I'd call it `channels` instead of `tracks`
